sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t mirks/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mirks/react-test npm test

# push to docker hub, login to docker cli w/ travis, push built images to docker hub
after_success:
  - docker build -t mirks/multi-client ./client
  - docker build -t mirks/multi-nginx ./nginx
  - docker build -t mirks/multi-server ./server
  - docker build -t mirks/multi-worker ./worker
  #  docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mirks/multi-client
  - docker push mirks/multi-nginx
  - docker push mirks/multi-server
  - docker push mirks/multi-worker